### ISSUE TITLE
Klasa EmptyCell

### ISSUE THREAD

**Issue by maro512** [maro512/Loop#5]
Pusta komórka, jeżeli dostaje informacje, że ma drugiego sąsiada tego samego koloru, "zamienia" się w Tile. Dziedziczy po Cell

**Comment by maro512** [comment]
Nie byłoby łarwiej zapamiętywać zamiast ilości białych/czarnych sąsadów, zrobić booleana, czy jest biały albo czarny? Jak nie ma to ustawiasz, ze jest, a jak jest to zamieniasz na Tile, bo jest jednoznacznie wyznaczony

**Comment by pzjp** [comment]
ale co jest białe czy czarne? Możesz mieć białe i czarne linie z różnych stron. Jak zapamiętuję je w maskach, to potem mogę łatwo stworzyć płytkę (w naturalny sposób, bez nadmiernych rozgałęzień, a tylko z kilkoma niegroźnymi bitowymi operacjami). Poza tym może dojść do sytuacji, że nic nie pasuje (raczej nie w normalnej grze, ale jak ktoś by się z nudów bawił w samo układanie płytek...). Tworzenie płytki nie może mieć miejsca w chwili gdy przypinam sąsiada, bo może się okazać, że zaraz miałem przypiąć następnego i się posypie.
Chciałem uniknąć dublowania obliczeń związanych z wyznaczaniem pasującej płytki (isDetermined() i createTile()). To nie są wielkie koszty, ale...
